FROM rockylinux:9

WORKDIR /app
COPY . .

RUN dnf install -y cargo openssl-devel lm_sensors-devel
RUN cargo install cargo-generate-rpm
RUN cargo build --release --all-features
RUN cargo clean -p minmon
RUN strip -s target/release/minmon
RUN cargo generate-rpm
RUN dnf install -y /app/target/generate-rpm/*.rpm

ENTRYPOINT ["/usr/bin/minmon"]
CMD ["/etc/minmon.toml"]